// <auto-generated />
namespace DAEA_LAB11_JE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2StudentUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2StudentUp));
        
        string IMigrationMetadata.Id
        {
            get { return "202206050254111_v2-StudentUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
